function out =  u(x,z,L,lambda,mu)
out = lambda.*mu.^(-1/2) .*csch (L.*mu.^(1/2)).*sinh (x.*mu.^(1/2)).*sinh((L+(-1).*z).*mu.^( ...
1/2)).*(x<z) + lambda.*mu.^(-1/2).*csch (L.*mu.^(1/2)).*sinh ((L+(-1).* ...
x).*mu.^(1/2)).*sinh(z.*mu.^(1/2)).*(x>=z);

%if x<z
%out = lambda.*mu.^(-1).*csch(L.*mu).*sinh(x.*mu).*sinh((L+( ...
%-1).*z).*mu);
%else  
%out = lambda.*mu.^(-1).*csch(L.*mu).*sinh((L+( ...
%-1).*x).*mu).*sinh(z.*mu);
end