function out =  ulambda(x,z,L,lambda,mu)
out = mu.^(-1/2).*csch (L.*mu.^(1/2)).*sinh (x.*mu.^(1/2)).* ...
sinh((L+(-1).*z).*mu.^(1/2)).*(x<z).*(1.0)+...
mu.^(-1/2).*csch (L.*mu.^( ...
1/2)).*sinh ((L+(-1).*x).*mu.^(1/2)).*sinh(z.*mu.^(1/2)).*(x>=z).*(1.0);
end